language: python
dist: jammy
python:
- 3.11
install:
- pip install -r requirements_dev.txt
script: tox
before_deploy:
- rm -rf src/debiased_sd.egg-info
- git stash --all
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ErikinBC
  password:
    secure: oLnfPsgjsSf9A+SKXEAZXJdZ0jviGGgURpQDtMrN5/9Kivbh2DZHC/mfYJGmTH7sDul3SjEHcAfc+W4U28cBHYqA+M8OQ+e2KG41vx77BonOoI50UUhPLOxQFT1Pr5H4msf5WAao/BoephEltVYqtF4pXJb+kox2FySmQzsAEute0obAS7LUklkC/lw8apSF3l135qqAJuz0WUgq+aJyssxVp0QqVJ3xROIBK5g0QjNDu2coRa88BPm0J5V1/d2/N6u/1W5Eqzo1aF3x7CTMJCe+ePQev4Uu4eQatVe4TVw8ENCRAi4tRTU7CC8YBkrmIPlVqdYQ/Lboh1AYq4aoPfPx+IQOGNYO1vbSauoN88k1hNVQPfI8JJF0HZGg6VWCo1NjMn/Y/oiKqooPG6iqGA7H30nCwe5ky+7htawvkfiB0AFOIcsLBG9BknUkkMZsLUtqrA4u569/b0V6xjyA9ss0sV/xMI36ZaY/v8Bl3Ex29CpvRcJkQvmv3wTRnxCb0yCUABWRr1C4XoQEG2jIRkCdLAu474CvDENzkKxWnvhml2VcpB31FJRuFvexOqO0IpQfQh+LfsSX5pjetStdtBtxTqdOYyVMj8Ejcs5O275ZeTZkF1VNrYXPB+wXzXhXHBACcoju6YEPDGthk8Z7bbe5NWPUk0omT+ki37rDoXU=
  on:
    repo: ErikinBC/debiased_sd
    branch: production
    python: 3.11
